DROP TABLE IF EXISTS test_results CASCADE;
DROP TABLE IF EXISTS test_assignments CASCADE;
DROP TABLE IF EXISTS answer_options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP SEQUENCE IF EXISTS users_id_seq CASCADE;
DROP SEQUENCE IF EXISTS tests_id_seq CASCADE;
DROP SEQUENCE IF EXISTS questions_id_seq CASCADE;
DROP SEQUENCE IF EXISTS answer_options_id_seq CASCADE;
DROP SEQUENCE IF EXISTS test_assignments_id_seq CASCADE;
DROP SEQUENCE IF EXISTS test_results_id_seq CASCADE;

SELECT 'All tables and sequences dropped successfully!' AS status;
